# This workflow copy content modified in the main branch to production branch.

name: CopyContentFolder

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # I actually disable this workflow to run as we don't need this any more.
  push:
    branches: [ main1 ]
    paths:
      - 'content/**'
  pull_request:
    branches: [ main1 ]
    paths:
      - 'content/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          threed:
            - 'content/3d/**'
          barcode:
            - 'content/barcode/**'
          cad:
            - 'content/cad/**'
          cells:
            - 'content/cells/**'
          diagram:
            - 'content/diagram/**'
          drawing:
            - 'content/drawing/**'
          email:
            - 'content/email/**'
          finance:
            - 'content/finance/**'
          font:
            - 'content/font/**'
          gis:
            - 'content/gis/**'
          html:
            - 'content/html/**'
          imaging:
            - 'content/imaging/**'
          note:
            - 'content/note/**'
          ocr:
            - 'content/ocr/**'
          omr:
            - 'content/omr/**'
          page:
            - 'content/page/**'
          pdf:
            - 'content/pdf/**'
          psd:
            - 'content/psd/**'
          pub:
            - 'content/pub/**'
          slides:
            - 'content/slides/**'
          svg:
            - 'content/svg/**'
          tasks:
            - 'content/tasks/**'
          tex:
            - 'content/tex/**'
          total:
            - 'content/total/**'
          words:
            - 'content/words/**'
          zip:
            - 'content/zip/**'

    - name: Copy 3d Content
      if: steps.filter.outputs.threed == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/3d
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy barcode Content
      if: steps.filter.outputs.barcode == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/barcode
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy cad Content
      if: steps.filter.outputs.cad == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/cad
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy cells Content
      if: steps.filter.outputs.cells == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/cells
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy diagram Content
      if: steps.filter.outputs.diagram == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/diagram
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy drawing Content
      if: steps.filter.outputs.drawing == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/drawing
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy email Content
      if: steps.filter.outputs.email == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/email
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy finance Content
      if: steps.filter.outputs.finance == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/finance
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy font Content
      if: steps.filter.outputs.font == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/font
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy gis Content
      if: steps.filter.outputs.gis == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/gis
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy html Content
      if: steps.filter.outputs.html == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/html
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy imaging Content
      if: steps.filter.outputs.imaging == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/imaging
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy note Content
      if: steps.filter.outputs.note == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/note
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy ocr Content
      if: steps.filter.outputs.ocr == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/ocr
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy omr Content
      if: steps.filter.outputs.omr == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/omr
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy page Content
      if: steps.filter.outputs.page == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/page
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy pdf Content
      if: steps.filter.outputs.pdf == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/pdf
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy psd Content
      if: steps.filter.outputs.psd == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/psd
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy pub Content
      if: steps.filter.outputs.pub == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/pub
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy slides Content
      if: steps.filter.outputs.slides == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/slides
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy svg Content
      if: steps.filter.outputs.svg == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/svg
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy tasks Content
      if: steps.filter.outputs.tasks == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/tasks
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy tex Content
      if: steps.filter.outputs.tex == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/tex
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy total Content
      if: steps.filter.outputs.total == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/total
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy words Content
      if: steps.filter.outputs.words == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/words
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main

    - name: Copy zip Content
      if: steps.filter.outputs.zip == 'true'
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: ./content/zip
        dst_path: /content/
        dst_owner: Aspose
        dst_repo_name: products.aspose.com
        dst_branch: production
        src_branch: main
